//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VersiondogReportService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B4M")]
        public string Datenbank_User {
            get {
                return ((string)(this["Datenbank_User"]));
            }
            set {
                this["Datenbank_User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tb%-3jR7bs$kds9kgKhds087")]
        public string Datenbank_Passwort {
            get {
                return ((string)(this["Datenbank_Passwort"]));
            }
            set {
                this["Datenbank_Passwort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rb0orarac35.de.bosch.com")]
        public string Datenbank_Host {
            get {
                return ((string)(this["Datenbank_Host"]));
            }
            set {
                this["Datenbank_Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T_VERSIONDOGREPORTING")]
        public string Datenbank_Tabelle {
            get {
                return ((string)(this["Datenbank_Tabelle"]));
            }
            set {
                this["Datenbank_Tabelle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"\\BA0vm060\vDogReports$\AutoImport:5:BaP:false;\\BU4PTEFAPP04.emea.bosch.com\vDogReports\AutoImport:4:BuP:false;\\chvmhdev6vd.us.bosch.com\vDogReports\AutoImport:4:ChP:false;\\bljvm120.emea.bosch.com\vDogReports\AutoImport:5:BljP:false;\\ad0vmvrsndog.us.bosch.com\vDogReports\AutoImport:5:AnP:false;\\fe0vm03418.de.bosch.com\vDogReports$\AutoImport:5:FeP:false")]
        public string Export_Ordnerpfade {
            get {
                return ((string)(this["Export_Ordnerpfade"]));
            }
            set {
                this["Export_Ordnerpfade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3600000")]
        public int Timer_Tick {
            get {
                return ((int)(this["Timer_Tick"]));
            }
            set {
                this["Timer_Tick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ASS1368_rb0orarac35.de.bosch.com")]
        public string Datenbank_SID {
            get {
                return ((string)(this["Datenbank_SID"]));
            }
            set {
                this["Datenbank_SID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("38000")]
        public string Datenbank_Port {
            get {
                return ((string)(this["Datenbank_Port"]));
            }
            set {
                this["Datenbank_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T_VERSIONDOG_REFERENCLINES")]
        public string Datenbank_reference_Tabelle {
            get {
                return ((string)(this["Datenbank_reference_Tabelle"]));
            }
            set {
                this["Datenbank_reference_Tabelle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T_VDOGZUWEISUNG")]
        public string Datenbank_Zuweisung {
            get {
                return ((string)(this["Datenbank_Zuweisung"]));
            }
            set {
                this["Datenbank_Zuweisung"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\VersiondogReportingServiceOracle\\VersiondogReportService\\bin\\Debug\\ComponentTr" +
            "eeSchema.xsd")]
        public string XmlSchemaFile {
            get {
                return ((string)(this["XmlSchemaFile"]));
            }
            set {
                this["XmlSchemaFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\VersiondogReportingServiceOracle\\VersiondogReportService\\bin\\Debug\\ComponentTr" +
            "eeSchema_new.xsd")]
        public string XmlSchemaFile_UpperCase {
            get {
                return ((string)(this["XmlSchemaFile_UpperCase"]));
            }
            set {
                this["XmlSchemaFile_UpperCase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T_VDOGZUWEISUNG")]
        public string Datenbank_Tabelle_Zuweisung {
            get {
                return ((string)(this["Datenbank_Tabelle_Zuweisung"]));
            }
            set {
                this["Datenbank_Tabelle_Zuweisung"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\ba0vm060\\vDogReports$")]
        public string Export_Componenten_Ordnerpfad {
            get {
                return ((string)(this["Export_Componenten_Ordnerpfad"]));
            }
            set {
                this["Export_Componenten_Ordnerpfad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LASTCHECK;NEXTSTART;JOBSTART;JOBFINISH;TIMESTAMPBACKUP;TIMESTAMPPREBACKUP")]
        public string Csv_DateTime_Columns {
            get {
                return ((string)(this["Csv_DateTime_Columns"]));
            }
            set {
                this["Csv_DateTime_Columns"] = value;
            }
        }
    }
}
